### ISSUE TITLE
Add documentation for new phone number component

### ISSUE THREAD

**Issue by froschdesign** [laminas/laminas-i18n#90]
https://github.com/laminas/laminas-i18n-phone-number

**Comment by froschdesign** [comment]
@gsteel 
For version 3 I suggest a simple solution to integrate the phone number documentation via Makefile:

```Makefile
LAMINAS_I18N_PHONE_NUMBER_VERSION := 1.6.0
LAMINAS_I18N_PHONE_NUMBER_TMP := docs/tmp

fetch-laminas-i18n-phone-number-docs:
	rm -rf $(LAMINAS_I18N_PHONE_NUMBER_TMP)
	git clone --depth 1 --filter=blob:none --sparse \
		--branch $(LAMINAS_I18N_PHONE_NUMBER_VERSION) \
		https://github.com/laminas/laminas-i18n-phone-number.git \
		$(LAMINAS_I18N_PHONE_NUMBER_TMP)
	cd $(LAMINAS_I18N_PHONE_NUMBER_TMP) && \
		git sparse-checkout set docs/book
	mkdir -p docs/book
	cp -R $(LAMINAS_I18N_PHONE_NUMBER_TMP)/docs/book/. docs/book/v3/phone-number
	rm -rf $(LAMINAS_I18N_PHONE_NUMBER_TMP)
```

```yaml
nav:
    - Home: index.md
    - v3:
        - …
        - Filters:
            - …
            - ToE164: v3/phone-number/filters/to-e164.md
            - ToInternationalPhoneNumber: v3/phone-number/filters/to-international-phone-number.md
            - ToNationalPhoneNumber: v3/phone-number/filters/to-national-phone-number.md
        - "Form Elements":
           -  PhoneNumber: v3/phone-number/element/phone-number.md
        - Validators:
            - …
            - PhoneNumber: v3/phone-number/validators/phone-number.md
            - …
        - 'View Helpers':
            - …
            - PhoneNumberFormat: v3/phone-number/helper/phone-number-format.md
```

This isn’t a solution for all the other repositories, but at least we’ve used it to fill in the missing documentation for now.
